# Generated by Django 5.0.3 on 2024-03-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("opis", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gotvac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("bio", models.CharField(max_length=30)),
                ("borndate", models.CharField(max_length=30)),
                ("profileImage", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Recept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("opis", models.TextField()),
                ("ingridians", models.TextField()),
                ("instructions", models.TextField()),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.category"
                    ),
                ),
                (
                    "sheff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.gotvac"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("IT", "Italian"),
                            ("FC", "France"),
                            ("MKD", "Macedonian"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.gotvac"
                    ),
                ),
                ("recept", models.ManyToManyField(to="app.recept")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField()),
                ("comment", models.TextField()),
                ("inputDate", models.DateField()),
                (
                    "recept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.recept"
                    ),
                ),
            ],
        ),
    ]
