# Generated by Django 5.0.3 on 2024-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_book_meal_type_nagrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gotvac",
            name="profileImage",
            field=models.ImageField(upload_to=""),
        ),
    ]
