# Generated by Django 5.0.3 on 2024-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_gotvac_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="slika",
            name="slika_url",
            field=models.URLField(null=True, unique=True),
        ),
    ]
