# Generated by Django 5.0.6 on 2024-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
