# Generated by Django 5.0.6 on 2024-06-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbands',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
