# Generated by Django 5.0.6 on 2024-06-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='reserved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room'),
        ),
    ]
