# Generated by Django 5.0.6 on 2024-06-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_alter_hotels_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('хигеничар', 'хигеничар'), ('рецепционер', 'рецепционер'), ('менаџер', 'менаџер')], max_length=20, null=True),
        ),
    ]
