# Generated by Django 5.0.6 on 2024-05-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('founded_year', models.PositiveIntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='books')),
                ('isbn', models.CharField(max_length=50)),
                ('year_published', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('dimensions', models.CharField(max_length=50)),
                ('cover_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Romance', 'Романса'), ('Thriller', 'Трилер'), ('Biography', 'Биографија'), ('Classic', 'Класик'), ('Drama', 'Драма'), ('History', 'Историја')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBook.publisher')),
            ],
        ),
    ]
